name: Genome Architect
title: Manual for Apollo
markdown: kramdown
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]
